dependencies {
	compileOnly group: "com.graphql-java", name: "graphql-java", version: "11.0"
	compileOnly group: "io.github.graphql-java", name: "graphql-java-annotations", version: "6.2"
	compileOnly group: "com.graphql-java", name: "java-dataloader", version: "2.0.2"

	compileOnly group: "javax.ws.rs", name: "javax.ws.rs-api", version: "2.0.1"
	compileOnly project(":apps:oauth2-provider:oauth2-provider-scope-api")
	compileOnly project(":apps:portal-vulcan:portal-vulcan-api")
}